=== Antoha5001/xml.xslt/app/less3/lab-3-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:group name="contactGroup">
        <xsd:sequence>
            <xsd:element name="first" type="xsd:string"/>
            <xsd:element name="last" type="xsd:string"/>
            <xsd:element name="middle" type="xsd:string"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:complexType name="nameType">
        <xsd:sequence>
            <xsd:group ref="contactGroup"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="employeeType">
        <xsd:sequence>
            <xsd:element name="phone">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="mobile" type="xsd:boolean" use="optional"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="email" type="xsd:string"/>
            <xsd:element name="name" type="nameType"/>
            <xsd:any minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:element name="age" type="xsd:integer"/>
    <xsd:complexType name="personalType">
        <xsd:sequence>
            <xsd:element name="employee" type="employeeType"  minOccurs="0" maxOccurs="2"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="extPersonal">
        <xsd:complexContent>
            <xsd:extension base="personalType">
                <xsd:sequence>
                    <xsd:element name="minCount" type="xsd:integer"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:maxExclusive value="7"/>
            <xsd:minExclusive value="2"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="personal" type="personalType"/>

</xsd:schema>

=== Antoha5001/xml.xslt/app/less3/lab-3-1.xml
<?xml version="1.0" encoding="utf-8"?>
<personal
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lab-3-1.xsd">
  <employee id="e-1">
      <phone mobile="true">123</phone>
      <email>sdfsfd</email>
      <name>
          <first>Adfg</first>
          <last>xcvxc</last>
          <middle>sdfsf</middle>
      </name>
      <age>111</age>
  </employee>
  <employee id="e-2">
      <phone>123</phone>
      <email>sdfsfd</email>
      <name>
          <first>Adfg</first>
          <last>xcvxc</last>
          <middle>sdfsf</middle>
      </name>
  </employee>
</personal>
