=== Antoha5001/xml.xslt/app/less3/lab-3-3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:group name="dateGroup">
        <xsd:sequence>
            <xsd:element name="date" type="xsd:string"/>
            <xsd:element name="time" type="xsd:string"/>
        </xsd:sequence>
    </xsd:group>
    <xsd:complexType name="lessonType">
        <xsd:sequence>
            <xsd:group ref="dateGroup"/>
        </xsd:sequence>
        <xsd:attribute name="no" type="xsd:integer"/>
    </xsd:complexType>

    <xsd:complexType name="time_tableType">
        <xsd:sequence>
            <xsd:element name="lesson" type="lessonType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="officeType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="address" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="code" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="officesType">
        <xsd:sequence>
            <xsd:element name="office" type="officeType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tableExp">
        <xsd:complexContent>
            <xsd:extension base="time_tableType">
                <xsd:sequence>
                    <xsd:element name="offices" type="officesType"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="time_table" type="tableExp"/>
</xsd:schema>

=== Antoha5001/xml.xslt/app/less3/less3.xml
<?xml version="1.0" encoding="utf-8"?>
<time_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="lab-3-3.xsd">
	<lesson no="1">
		<date>2017-06-08</date>
		<time>12:18:00</time>
	</lesson>
	<lesson no="2">
		<date>2017-06-08</date>
		<time>14:18:00</time>
	</lesson>
	<offices>
		<office code="БК">
			<name>комплекс "Бакунский"</name>
			<address>ул. Баккуaнская, 17</address>
		</office>
		<office code="РА">
			<name>комплекс "Радио"</name>
			<address>ул. Радио, д. 222</address>
		</office>
	</offices>
</time_table>
